model:
  name: "SalesLLM-10M"
  architecture: "GPT"
  
  vocab_size: 8000
  max_seq_length: 512
  embedding_dim: 256
  num_layers: 4
  num_heads: 4
  ff_dim: 1024
  dropout: 0.1

training:
  batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 3.0e-4
  weight_decay: 0.1
  max_epochs: 10
  warmup_steps: 100
  max_steps: -1
  
  optimizer: "AdamW"
  lr_scheduler: "cosine"
  max_grad_norm: 1.0
  
  save_every: 500
  eval_every: 250
  
  device: "cpu"
  mixed_precision: false
  compile_model: false

data:
  train_split: 0.9
  val_split: 0.1
  
  sources:
    - chat_logs
    - pdfs
    - images_ocr
  
  min_text_length: 50
  max_text_length: 2048

tokenizer:
  type: "BPE"
  vocab_size: 8000
  special_tokens:
    - "<|endoftext|>"
    - "<|pad|>"
    - "<|user|>"
    - "<|assistant|>"
    - "<|system|>"
    - "<|unk|>"
